palmetto/palm-dbt

- README.md
- [ X] Docs have been reviewed and added / updated if needed (for bug fixes / features)
A description of the problem you're trying to solve.
Any relevant logs, error output, etc.
An overview of the suggested solution
If the feature changes current behavior, reasons why your solution is better.
When attempting to set up palm in jaffle shop dbt demo project, I only had to run `palm init` not `palm scaffold init`
N/A
N/A
**Operating System:** …
> fixed init command documentation

- palm/plugins/dbt/commands/cmd_snapshot.py
Using the `palm-dbt` plugin to run `dbt snapshot` fails because the snapshot command is missing `dbt deps` (when a snapshot project runs `dbt_utils` or any other imported package's macros). This fix adds the standard long cycle and short cycle versions of the command with long cycle run by default.
…
…
**Operating System:** ...
> [BUG] Add `dbt deps` to `palm snapshot` command

- palm/plugins/dbt/commands/cmd_compile.py
- palm/plugins/dbt/commands/cmd_snapshot.py
- setup.py
`palm snapshot --select model1 model2` currently fails because the snapshot command fails to enumerate the objects in the tuple of select values. We previously fixed this for `palm run` and a few other commands, but failed to catch every instance.
This fix properly enumerates the items in the tuple captured with the `--select` flag or the `--model` flag for `palm compile` and `palm snapshot`.
…
…
> [BUG] Enumerate `--select/--model` options in `snapshot` and `compile`

- palm/plugins/dbt/commands/cmd_shell.py
This allows users to shell into their container and run arbitrary commands
useful for power users who need direct access to their underlying CLIs
and for debugging problems inside of the container
DATA-478
Pairs well with https://github.com/palmetto/palm-cli/pull/28/files
**Operating System:** MacOS
> DATA-478: Add shell command with dbt environment variables

- README.md
- palm/plugins/dbt/dbt_containerizer.py
- palm/plugins/dbt/sql_to_dbt.py
- palm/plugins/dbt/templates/containerize/docker-compose.yaml
- setup.py
- tests/unit/test_dbt_containerizer.py
[X] All new and existing tests pass locally (`palm test`) 
When containerizing an existing repository, palm will now follow dbt's pattern for finding the profiles.yml file. 
1. look for `DBT_PROFILES_DIR` envar. if it exists, use that to define the path to the file and mount it correctly.
2. define the path in `.env` so it can be unique for each user (absolute home paths are not the same ;) ) 
3. default to the dbt default, `~/.dbt`
4. if no profiles.yml exists, skip it completely
**Operating System:** MacOS
**Platform:** Monterey
**Target Platform:** All
> Use dbt's Native Profiles Resolution When Containerizing

- palm/plugins/dbt/commands/cmd_compile.py
- palm/plugins/dbt/commands/cmd_cycle.py
- palm/plugins/dbt/commands/cmd_run.py
- palm/plugins/dbt/commands/cmd_snapshot.py
- palm/plugins/dbt/commands/cmd_test.py
- palm/plugins/dbt/dbt_containerizer.py
- palm/plugins/dbt/dbt_palm_utils.py
- palm/plugins/dbt/sql_to_dbt.py
Older versions of Python will raise an error when typehints do not use the imported Type class from typing.
#30
**Operating System:**Mac OS
> Fix type hints for older versions of python (<3.9)

- palm/plugins/dbt/dbt_containerizer.py
This fixes incompatible syntax for < python3.8
**Operating System:** MacOS
**Platform:**Monterey
**Target Platform:**Python3.6, pyhon3.7
> Remove walrus operator

- palm/plugins/dbt/templates/containerize/Dockerfile.txt
The new structure for profiles introduced in #26 no longer expects profiles.yml in the repo. Which breaks this COPY statement. 
This will now work with the new, dbt-friendly behavior :) 
A description of the problem you're trying to solve.
Image will not build in current state :( 
**Operating System:** MacOS
**Platform:**Monterey
**Target Platform:**Python3.6, => python3.9
> Remove bad copy in Dockerfile

- .github/workflows/pull-request.yaml
- dev-requirements.txt
- tests/unit/test_dbt_containerizer.py
Bump python versions in testing matrix. palm-cli no longer supports python 3.6
> [HOTFIX] Adjust python version support to match palm-cli

- palm/plugins/dbt/commands/cmd_model-doc.py
- palm/plugins/dbt/requirements.txt
- palm/plugins/dbt/templates/model_docs/model_doc.tpl.md
- palm/plugins/dbt/templates/model_docs/template-config.yaml
Adds a new command to generate docs for new models!
- Requires one argument, the path (relative or absolute) to the model you want to generate docs for.
- Generates the model doc markdown file with some basic user input (grain and description)
- Generates the model yml file including:
- Parse the SQL to get a list of columns 
- If a column name matches an existing column doc, use that. Otherwise, add a placeholder with TODO
DATA-101 (Palmetto internal issue)
- Parsing the SQL may not be totally bulletproof. I have tested it against a few different models and ironed out the bugs I found.
- I'm not sure how 'standard' our structure of model docs is? Those of you who have used dbt other places, please think about the logic in …
> [FEATURE] DATA-101 Generate model docs

- palm/plugins/dbt/commands/cmd_model-doc.py
- palm/plugins/dbt/parsers/__init__.py
- palm/plugins/dbt/parsers/project_parser.py
- palm/plugins/dbt/templates/model_docs/model_doc.tpl.md
model-doc command now honors docs_path configuration
- Adds parsing for dbt_project
- Updates model-doc implementation to find all possible doc path matches
- If no matches, allow the user to manually enter a path
- If multiple matches, prompt user to select one
- Improve cli output when generating model docs by including the model name in f-strings
N/A
This solution does not introduce a breaking change and should work with any dbt_project configuration.
The addition of the dbt_project parser allows us to do much more with this!
> [FEATURE] Fix model doc

- palm/plugins/dbt/commands/cmd_model-doc.py
Update model-doc command to populate existing columns when a docs_path config is present
We recently fixed this issue for generating the model.md into the correct location but missed updating the function to find existing column-level docs
This change allows model-doc to work as designed, pre-populating existing column descriptions with the doc macro where possible
> [BUGFIX] Model doc populates existing column docs

- palm/plugins/dbt/commands/cmd_dbt.py
- palm/plugins/dbt/commands/cmd_model-doc.py
Many users are relying heavily on palm shell to allow control over the dbt commands they are running.
Adding a passthrough command allows users to run whatever commands they want inside the container.
palm dbt captures arguments as the command and allows the most common options, with the ability to specify an option string for any additional options that are needed
**Operating System:** macOs
**Platform:** dbt 1.2.x
**Target Platform:** dbt > 1.x (though it will work on lower versions)
> [FEATURE] Add palm dbt passthrough command

- palm/plugins/dbt/commands/cmd_run.py
- palm/plugins/dbt/commands/cmd_test.py
- palm/plugins/dbt/dbt_palm_utils.py
- Remove the shell_options utility to simplify dbt run and test commands and decouple their logic. This was a relic from the very first iteration of palm and causes tight coupling between these 2 core palm-dbt commands
- Removes unnecessary complexity and allows us to more easily reason about what a given command will do
- Passing locals as kwargs was fragile and didn't work 100% of the time
- Add exclude option to run and test
- Remove macro option from `palm run` - this was not being used and caused complex branching logic. With the new `palm dbt` passthrough command, users are able to execute `dbt run-operation` directly which is way more likely than remembering how the `--macros` option works.
- this change paves the …
> [FEATURE] Simplify run & test commands

- palm/plugins/dbt/commands/cmd_prod-artifacts.py
This is implemented as a no-op command as there are many places artifacts can be stored and many nuances to how they should be downloaded.
In the future, we may implement a mechanism to download from common storage locations (dbt cloud, GCS, S3) but we do not currently have bandwidth to do this and want to keep other valuable features moving.
Unblocks remaining work on #67 
**Operating System:** MacOs
**Platform:** python3.9
> [FEATURE] No-op Command for downloading prod artifacts

- palm/plugins/dbt/commands/cmd_run.py
The `build_run_command` had been updated to add `--full-refresh` to both `dbt run` and `dbt seed` commands when the flag was used, but there was already a condition to add on the flag to the `dbt run` command, resulting in it being appended on twice. Functionally, it still worked, but it was a goofy mistake that doesn't need to be there!
N/A
Nope
**Operating System:** Mac M1 Max, Ventura OS
> [BUGFIX] Appended `--full-refresh` flag twice

- palm/plugins/dbt/requirements.txt
dbt-core now depends on pyyaml 6.0, we want to make sure folks can install palm-dbt in an environment where they are running dbt on the metal. The good news is we just have to remove the version pin. All our `yaml.load` calls specify the loader
…
This change will need to be deployed along with a corresponding patch in palm cli (https://github.com/palmetto/palm-cli/pull/96)
> [FEATURE] Compatibility with pyyaml 6.0

- palm/plugins/dbt/commands/cmd_cycle.py
- palm/plugins/dbt/commands/cmd_run.py
- palm/plugins/dbt/commands/cmd_seed.py
Changes `palm run` and `palm cycle` to make seeds opt-in, rather than opt-out. This is preferable most of the time when working on regular models, which is the case for most dbt development tasks.
Defaults to `full-refresh` for seeds. This instructs dbt to recreate the seed table on each run, rather than inserting - this is necessary when making changes to seeds that have already been run on the current branch.
Adds a `palm seed` command to explicitly run seeds. This should be helpful when working on a seed, since we can `--select my_new_seed` for speed and efficiency.
DP-389 (Palmetto internal)
> Feature: seeds are opt in

- palm/plugins/dbt/commands/cmd_compile.py
- palm/plugins/dbt/commands/cmd_cycle.py
- palm/plugins/dbt/commands/cmd_model.py
- palm/plugins/dbt/commands/cmd_prod-artifacts.py
- palm/plugins/dbt/commands/cmd_run.py
- palm/plugins/dbt/commands/cmd_snapshot.py
- palm/plugins/dbt/commands/cmd_test.py
- palm/plugins/dbt/dbt_palm_utils.py
As we have developed `palm run` to be more refined, our other commands have fallen behind.
This PR updates `snapshot` , `test`, and `compile` to use the same selection flags, the `--defer` logic (where it can be used), and the other improvements that `palm run` enjoys like the newer method of building the commands, the new method of cleaning up after the run, and the flag shortcuts (eg. "-s"). This PR also fixes some comments to consistently lower-case dbt, converts these commands to also all use `@click.pass_obj` rather than `@click.pass_environment`, and makes sure all the commands with the `--clean` flag clean up in the same manner.
No
I tried to lint the codebase but couldn't--it said no config found
**Operating …
> [FEATURE] Consistent dbt command options

- palm/plugins/dbt/commands/cmd_compile.py
- palm/plugins/dbt/commands/cmd_run.py
- palm/plugins/dbt/commands/cmd_seed.py
- palm/plugins/dbt/commands/cmd_test.py
Adds the ability to use yaml selectors with palm-dbt commands.
No.
Not having this has started to be a thorn in my side
I'm running this locally and happy about it. (dbt v1.4)
> [FEATURE] Add support for yaml selectors to relevant commands

- palm/plugins/dbt/commands/cmd_run.py
- palm/plugins/dbt/commands/cmd_test.py
- palm/plugins/dbt/dbt_version_detection.py
- palm/plugins/dbt/plugin_config.py
- palm/plugins/dbt/requirements.txt
The change is semi-breaking, since it will require updating the plugin config...
- Adds dbt version to the plugin config.
- Implements automatic version detection when the plugin config is initialized or re-configured with `palm plugin configure --name dbt`
- Adds `semver` as a new dependency
- Adds utility functions to check whether the current version is greater or less than another version.
Resolves #88 
I don't love some of this... but it works.
Minimally tested in local dbt project.
MacOS.
No merge so I can take more time to test this.
> Feature: dbt Version detection & fix deprecation warnings in >= v1.5

- .github/CODEOWNERS
- CHANGELOG.md
- palm/plugins/dbt/commands/cmd_compile.py
- palm/plugins/dbt/commands/cmd_run.py
- palm/plugins/dbt/commands/cmd_seed.py
- palm/plugins/dbt/commands/cmd_test.py
- palm/plugins/dbt/dbt_version_detection.py
- palm/plugins/dbt/plugin_config.py
- palm/plugins/dbt/requirements.txt
- setup.py
> Release v0.8.0
