- CHANGELOG.md
- palm/plugins/dbt/commands/cmd_snapshot.py
- setup.py
Release changes from develop as v0.0.3
- See changelog for details
> Release v0.0.3

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Issue templates are missing! Let's add some.
> Enable issue templates

- palm/plugins/dbt/commands/cmd_cleanup.py
- palm/plugins/dbt/commands/cmd_compile.py
- palm/plugins/dbt/commands/cmd_cycle.py
- palm/plugins/dbt/commands/cmd_dbt-docs.py
- palm/plugins/dbt/commands/cmd_install.py
- palm/plugins/dbt/commands/cmd_model.py
- palm/plugins/dbt/commands/cmd_run.py
- palm/plugins/dbt/commands/cmd_snapshot.py
- palm/plugins/dbt/commands/cmd_test.py
- palm/plugins/dbt/dbt_palm_utils.py
- palm/plugins/dbt/dbt_plugin.py
- palm/plugins/dbt/local_user_lookup.py
- palm/plugins/dbt/sql_to_dbt.py
Run black for PEP8 formatting fixes across this project
> Run black to fix PEP8 warnings across the project

- palm/plugins/dbt/commands/cmd_model.py
- palm/plugins/dbt/sql_to_dbt.py
We had a hardcoded string that only works for one of our internal projects, we removed it.
--model-dir must now be passed as an option, we could potentially make that not required, but we'd have to add branching logic to handle both cases.
…
…
**Operating System:** …
> Remove hard-coded 'arbor'

- CHANGELOG.md
We needed a changelog for tonight's release!
…
…
> Adding changelog entry for 0.0.5

- .github/workflows/pull-request.yaml
- palm/plugins/dbt/sql_to_dbt.py
Add a GH action with a job to lint code on PRs
> Add pull request GH workflow with lint job

- .github/ISSUE_TEMPLATE/01_bug_report.md
- README.md
When debugging palm-dbt, it is helpful to know which plugin version is being used in addition to the palm version.
…
…
**Operating System:** …
> add palm-dbt version for debugging purposes

- palm/plugins/dbt/commands/cmd_containerize.py
Prompts are more user friendly for this, so we prompt!
> Prompt for dbt version incontainerize

- README.md
Clarify version selection in documentation.
This is related to issue #34 
**Operating System:** ...
> add version flag and explain version selection

- .github/workflows/pull-request.yaml
- dev-requirements.txt
- tests/unit/test_dbt_containerizer.py
* Add test step to pull request workflow
* Attempt to test multiple python versions in CI
Not sure whether this will work... need to see what the action does in CI!
> Add test job to pull request

- .github/workflows/pull-request.yaml
- dev-requirements.txt
Hard pin the version of black we are using to lint, ensures version matches between dev and CI
We made the same change in palm-cli recently!
> Pin black version

- .github/CODEOWNERS
No functional change, additional code owners
> Add Corey and Olivia as code owners

- .github/CODEOWNERS
> [CHORE] Add Evan as a codeowner

- .github/workflows/pull-request.yaml
- CHANGELOG.md
- setup.py
Bump version, add changelog, and fix python 3.10 version ready for ready for release
> [RELEASE] 0.3.0

- .github/CODEOWNERS
- .github/workflows/pull-request.yaml
- palm/plugins/dbt/commands/cmd_test.py
dbt test does not re-seed
There's never really a need to re-seed before running tests, this just slows down local dev and adds no value.
N/A
> [FEATURE] Better dbt test

- CHANGELOG.md
- setup.py
Release recent changes as a new patch version
> v0.3.1 release notes and config

- palm/plugins/dbt/commands/cmd_model-doc.py
Sometimes we might want to specify our column docs right here in the terminal, so let's make that possible!
It'd be nice to have the option to generate a column doc when manual descriptions are provided... but that requires a good amount more code. Added a TODO to add that feature at a later date.
> [FEATURE] Interactive column doc descriptions

- palm/plugins/dbt/commands/cmd_containerize.py
- palm/plugins/dbt/dbt_containerizer.py
- palm/plugins/dbt/templates/containerize/Dockerfile.txt
- tests/unit/test_dbt_containerizer.py
`palm-dbt` technically only officially supports dbt v0.19 through v0.22. It should support through the newest minor version of v1, since v1 has been out for a while and is stable and widely in use.
[#43](https://github.com/palmetto/palm-dbt/issues/43)!
…
**Operating System:** Mac OSX Big Sur
> [FEATURE] Update max version to support dbt V1

- palm/plugins/dbt/plugin_config.py
Allows projects without prod artifacts implemented to use this plugin.
Prod artifacts are not required for using palm-dbt, the config needs to be optional
> [HOTFIX] Optional prod artifact config

- palm/plugins/dbt/commands/cmd_snapshot.py
This matches the behavior of other commands in this plugin.
**Operating System:** MacOs
**Platform:** dbt v1+
> [FEATURE] snapshot command persist by default

- palm/plugins/dbt/commands/cmd_seed.py
Fix bad decorator in `palm seed`
MacOS
> [HOTFIX] Fix palm seed command

- .github/CODEOWNERS
> Update codeowners to use GH team
